project:
  type: website
  output-dir: docs
website:
  title: "Carly Baretz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resources.qmd 
        text: Tidy Tuesday Analysis

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual



  