project:
  type: website
  output-dir: docs
website:
  title: "Carly Baretz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Data Viz"
        menu: 
          - text: "Valentines Day"
            href: valentines.html
          - text: "Baby Names"
            href: babynames.html
      - Project2.qmd
      - Project3.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual



  