project:
  type: website
  output-dir: docs
website:
  title: "Carly Baretz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Data Visualization"
        menu: 
          - text: "Valentines Day Dataset"
            href: valentines.html
          - text: "Baby Names Dataset"
            href: babynames.html
      - text: "Netflix Data Analysis"
        href: Project2.html
      - text: "Mets vs Yankees Statistical Analysis"
        href: Project3.html
      - text: "Analysis of Scientific Research Data"
        href: Project4.html
      - presentation.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual



  